import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}>
        <div className="max-w-2xl mx-auto p-4 space-y-6">
          <Nav />
          {children}
        </div>
      </body>
    </html>
  );
}

function Nav() {
  return (
    <div className="flex justify-between items-center border-b border-white/10 pb-3">
      <div className="flex gap-2">
        <a className="btn-ghost" href="/">Home</a>
        <a className="btn-ghost" href="/tasks">Tasks</a>
        <a className="btn-ghost" href="/wallet">Wallet</a>
        <a className="btn-ghost" href="/upload">Upload</a>
        <a className="btn-ghost" href="/u/me">Profile</a>
      </div>
      <AuthButtons />
    </div>
  );
}

function AuthButtons() {
  return (
    <form action="/api/auth/logout" method="post" className="flex gap-2 items-center">
      <a className="btn-ghost" href="/auth/login">Login</a>
      <a className="btn-ghost" href="/auth/register">Register</a>
      <button className="btn" type="submit">Logout</button>
    </form>
  );
}
