import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="max-w-2xl mx-auto p-4 space-y-6">
          <Nav />
          {children}
        </div>
      </body>
    </html>
  );
}

function Nav() {
  // client navigation bar via a simple client component wrapper
  return (
    <div className="flex justify-between items-center border-b pb-2">
      <div className="flex gap-4">
        <a href="/">Home</a>
        <a href="/tasks">Tasks</a>
        <a href="/wallet">Wallet</a>
      </div>
      <AuthButtons />
    </div>
  );
}

function AuthButtons() {
  return (
    <form action="/api/auth/logout" method="post">
      <a className="mr-3 underline" href="/auth/login">Login</a>
      <a className="mr-3 underline" href="/auth/register">Register</a>
      <button className="px-3 py-1 border" type="submit">Logout</button>
    </form>
  );
}
